### ISSUE TITLE
failed to create scores.json after the latest commit

### ISSUE THREAD

**Issue by amosbird** [gsamokovarov/jump#11]
Hi, after the atomic rename commit, I observed this error

```
renameat(AT_FDCWD, "/tmp/jump033116582", AT_FDCWD, "/home/amos/.jump/scores.json") = -1 EXDEV (Invalid cross-device link)
```

In archlinux, `/tmp` is a tmpfs which i suppose may conflict with the renaming here.

**Comment by gsamokovarov** [comment]
Great catch! I think I can do it in the same dir as the config, to avoid this. Let me try it and will get back to you with a new build.

**Comment by gsamokovarov** [comment]
Can you the latest master? 09c908a

**Comment by amosbird** [comment]
Thanks! It works fine now.
