### ISSUE TITLE
jump clean doesn't clean at all

### ISSUE THREAD

**Issue by amosbird** [gsamokovarov/jump#13]
Hi, it seems after using the temp file renaming, `jump clean` stops working.

**Comment by gsamokovarov** [comment]
What environment are you on? I just tested a `jump clean` run and it did clean up for my macOS install.

**Comment by amosbird** [comment]
I'm on centos 7. There are hundreds of dirs being cleaned. I'm not sure if that matters.

**Comment by gsamokovarov** [comment]
Cleaning here means, removing them from the database only. Have you used any network or remote storages that are not mounted now? Is the output of `jump clean` the same every time?

**Comment by amosbird** [comment]
I use local disk, and yep, `jump clean` outputs the same list everytime

**Comment by gsamokovarov** [comment]
Is your `~/.jump/scores.json` file too sensitive? Can you send it to me in a mail or secret gist, so I can try it locally?

**Comment by amosbird** [comment]
OK, I've sent it to you :)

**Comment by amosbird** [comment]
Hmm, it seems to be related to the upgrade of go.  After recompile `jump` it works again :)
