### ISSUE TITLE
err: no entries in the database

### ISSUE THREAD

**Issue by kolinsol** [gsamokovarov/jump#14]
I am getting this error "err: no entries in the database" on every attempt to use your program.
installed via homebrew.

**Comment by gsamokovarov** [comment]
@kolinsol did you integrated it with your shell? See the instructions on: https://github.com/gsamokovarov/jump#integration

**Comment by gsamokovarov** [comment]
Assuming that this was the issue, I have now put a descriptive message on jump's first run. Hopefully this will help newcommers. ❤️

```
♡  env JUMP_HOME=~/jump2 jump cd asdasd
Jump's database is empty. This could mean:

1. You are running jump for the first time. Have you integrated jump with your
   shell? Run the following command for help:

      $ jump shell

   If you have run the integration, enter a few directories in a new shell to
   populate the database.

2. The database is corrupted. You can open an issue on jump's issue tracker
   at https://github.com/gsamokovarov/jump/issues.
```
