### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by buchanae** [gsamokovarov/jump#15]
It would be best if jump was a substitute for `cd`. In order to do that, it needs to fallback to my existing habits when it can't provide a better match.

For example, I just started with jump 5 minutes ago. The first thing I did was `j /mn<tab>` because a) my database is empty b) I need to get to `/mnt/path/to/foo`. Normally I would `cd /mn<tab> p<tab> etc...` to tab complete each path.

But what I actually get is:
```
buchanan01 home
j /mn <cursor here after tab>
```

It's hard to display here, but my pattern of tab completion just inserted a space. I guess for now, the workaround is to rely on `cd` until I feel `jump` is doing a good job, but in reality switching between the two commands might not work out, and I might forget about jump.

**Comment by gsamokovarov** [comment]
This is way out of jump usage ideas. It is not meant as a `cd` replacement, but more of an `alias prj /full/path/project` helper.
