### ISSUE TITLE
Build cross-platform binaries and upload to releases page.

### ISSUE THREAD

**Issue by buchanae** [gsamokovarov/jump#16]
It's super easy to build cross-platform binaries in Go, and makes it really easy to download a command as a user.

**Comment by gsamokovarov** [comment]
I have packages for the Debian and RedHat based distributions in every release: https://github.com/gsamokovarov/jump/releases. Isn't that easier for you to install? What kind of distro are you using?

**Comment by buchanae** [comment]
haha, no. Nothing is easier than downloading a single file and putting it where ever I want. Using dpkg directly is not common, and most people don't have `sudo` access.

Anyway, why not add binaries to your releases?

**Comment by gsamokovarov** [comment]
Nobody requested this until now. 😅
