### ISSUE TITLE
command not found: No

### ISSUE THREAD

**Issue by ortonomy** [gsamokovarov/jump#17]
When I put 

``eval "$(jump shell)"`` in my ``~/.zshrc`` file, I get ``zsh: command not found: No`` error.

Any ideas?

**Comment by gsamokovarov** [comment]
`jump shell` uses the `SHELL` environment variable to guess the shell, can you try with: `eval "$(jump shell zsh)"`

Also, can you paste me the output of (if the command above doesn't work):

```
$ jump shell
# or
$ jump shell zsh
```

**Comment by luhova** [comment]
I get the same error on Ubuntu 18.04:

**Comment by luhova** [comment]
I get the same error on Ubuntu 18.04: 
```
/home/gabi/.zshrc:81: command not found: jump
♥ ~  jump shell
zsh: command not found: jump
♥ ~  jump shell zsh
zsh: command not found: jump
```

**Comment by gsamokovarov** [comment]
@luhova maybe you uninstalled jump? The error is that the command `jump` isn't available. How have you installed it recently?

**Comment by luhova** [comment]
@gsamokovarov oh yes, it was my mistake. Everything works fine now!

**Comment by marko-radosavljevic** [comment]
I'm facing the same issue, tried `eval "$(jump shell)"` and `eval "$(jump shell zsh)"` in .zshrc. Any info on this? @gsamokovarov 
```
❯ echo $SHELL
/usr/bin/zsh
------------------------------
❯ source .zshrc
(eval):1: command not found: No
------------------------------
❯ jump shell    
No such mark: shell
------------------------------
❯ jump shell zsh
No such mark: shell
------------------------------
❯ cd
No such mark: chdir
------------------------------
❯ j x(tab)
❯ j No\ such\ mark:\ hint
```
```
System Info   : 

OS            : Ubuntu 20.04.1 LTS x86_64
Kernel        : 5.8.0-36-generic
Shell         : zsh 5.8
Terminal      : terminator


Software Info : 

Package       : jump
Version       : 0.30.1
Status        : install ok installed

```

**Comment by gsamokovarov** [comment]
You may be having a shell function that's called `jump`. Can you give me the output of `which jump`?

**Comment by marko-radosavljevic** [comment]
Did not expect that...
```
❯ which jump
jump () {
	builtin cd -P "$MARKPATH/$1" 2> /dev/null || {
		echo "No such mark: $1"
		return 1
	}
}
❯ whereis jump
jump: /usr/bin/jump /usr/share/man/man1/jump.1
❯ whatis jump
jump (1)             - navigate faster by learning your habits
```

<details>
  <summary>apot show jump</summary>
  
Package: jump
Version: 0.30.1
Status: install ok installed
Priority: extra
Section: default
Maintainer: Genadi Samokovarov <gsamokovarov@gmail.com>
Installed-Size: 3,878 kB
Homepage: https://github.com/gsamokovarov/jump
License: MIT
Vendor: Genadi Samokovarov
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Jump helps you navigate faster by learning your habits.

</details>

**Comment by gsamokovarov** [comment]
This may be brought by another package or `oh-my-zsh` and the likes, if you use them. You may wanna chase what have brought this in and disable (or remove) it.

**Comment by marko-radosavljevic** [comment]
Yup, thanks for the help, much appreciated! ^^ :heart: 

For anyone stumbling upon this, it was [jump](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/jump) plugin from `oh-my-zsh`.

**Comment by gsamokovarov** [comment]
Thanks for trying out jump and I hope you like it!
