### ISSUE TITLE
Question: install without sudo?

### ISSUE THREAD

**Issue by asanakoy** [gsamokovarov/jump#19]
Hi,

Is it possible to install `jump` locally without sudo permissions?

**Comment by gsamokovarov** [comment]
@asanakoy Are you running linux? I can upload a linux binary on the latest release, if this will work for you. Other than that, you can try `go get github.com/gsamokovarov/jump` if you have the Golang toolchain installed.

**Comment by asanakoy** [comment]
I will try to use go. Thank you!

**Comment by gsamokovarov** [comment]
Great! I'm closing this issue, feel free to reopen if you need the statically compiled binary on the release page: https://github.com/gsamokovarov/jump/releases/tag/v0.20.0.

The packages include a man page, but nothing more than that. Please, don't hesitate to open issues if you have any troubles while using jump. 🙇‍♂️
