### ISSUE TITLE
Error appears in terminal

### ISSUE THREAD

**Issue by gerard-mailtrack** [gsamokovarov/jump#2]
I'm seeing this error in the terminal, whenever I run any command.

```
err: json: cannot unmarshal string into Go value of type scoring.Entries
```

**Comment by gsamokovarov** [comment]
What system are you running `jump` on?

You may try to remove the internal JSON database. You can do that with `rm ~/.jump/scores.json`.

**Comment by gerard-mailtrack** [comment]
Platform is Linux.

Removing the json did the trick. Thanks!

**Comment by gsamokovarov** [comment]
Please, ping me if it happens again. I'm curious what might have corrupted it.

Thanks for trying out jump!

**Comment by bwagner** [comment]
I was seeing a similar error when running this script a few times in a row: https://media.pragprog.com/titles/bhtmux/code/scripting/reattach/development

That script does a few asynchronous `cd` commands. I suspect that `jump` is not protecting itself against multiple instances writing the json files.

I suggest `jump` to:
1. test its json-files before using them (and suggesting to delete them when corrupt)
2. allow the user to delete them with a command line option
3. itself to be thread safe

**Comment by gsamokovarov** [comment]
I'll try to prevent multiple instances fighting for the scores update.

**Comment by gsamokovarov** [comment]
Try out `0.7.0`. I have put an advisory lock around the internal files write. Hopefully, this prevents issues like this one in the future.
