### ISSUE TITLE
5/5 review in Linux-Magazin 07/2018

### ISSUE THREAD

**Issue by robbiemorrison** [gsamokovarov/jump#20]
Jump 0.19.0 received five out of five stars in a recent review in Linux-Magazin 07/2018. The following URL provides a paywalled link (priced at €0.99) to that review:

- http://www.linux-magazin.de/ausgaben/2018/07/tooltipps-5/

With best wishes, Robbie

**Comment by gsamokovarov** [comment]
Sweet, thanks for the review! 💪
