### ISSUE TITLE
AUR package for ArchLinux

### ISSUE THREAD

**Issue by dufferzafar** [gsamokovarov/jump#22]
There is an old AUR package here: https://aur.archlinux.org/packages/jump-git

But it builds from source and hence requires Go toolchain to be setup on your machine.

The release page only has .deb & .rpm files. If it also had the raw binary itself, then I could create an AUR package (it's pretty easy!) 

So this kind of depends on #16

**Comment by gsamokovarov** [comment]
I have uploaded the binary on the latest release: https://github.com/gsamokovarov/jump/releases/tag/v0.20.0

**Comment by dufferzafar** [comment]
I've added an AUR package: https://github.com/dufferzafar/arch-packages/tree/master/jump-bin

**Comment by dufferzafar** [comment]
Anybody who uses Arch based distros will not really like this solution.

People prefer to install from AUR because it gives them updates etc.

I haven't yet figured out how to upload packages to the AUR repo (and I don't plan to either.)

Because even though I've created these packages, I'm not willing to maintain them.

**Comment by gsamokovarov** [comment]
Okay, this is fine then.

**Comment by ortonomy** [comment]
@gsamokovarov -- do you have a latest Arch AUR? does it work?
