### ISSUE TITLE
XDG Base Directory support or configurable path of database

### ISSUE THREAD

**Issue by onemanstartup** [gsamokovarov/jump#32]
Please support https://wiki.archlinux.org/index.php/XDG_Base_Directory by default if $XDG_DATA_HOME is set or provide environment key to modify path to database.

Thanks

**Comment by gsamokovarov** [comment]
The default location of the database is in `$HOME/.jump` and you can configure it by setting `$JUMP_HOME`. I can look into XDG support, but can you brief me about it? Is it the de-facto standard for newer unix tools?

**Comment by onemanstartup** [comment]
@gsamokovarov I hope so :)
 Not everyone supports this, but as you can see many are support this. Don't what else can I say.

**Comment by gsamokovarov** [comment]
Cool, I'll try to see what the other tools are doing and schedule it for the next release.

**Comment by gsamokovarov** [comment]
We'll have support for XGD in the next release! 🎉
