### ISSUE TITLE
Feature request: Integrate with the Ranger File Manager

### ISSUE THREAD

**Issue by jcklpe** [gsamokovarov/jump#33]
Similar to this plugin that works with autojump: https://github.com/fdw/ranger-autojump

**Comment by gsamokovarov** [comment]
Haven't used ranger, but I will take a look and get back to you. If it's easy to support, I don't mind the integration.

**Comment by gsamokovarov** [comment]
Here is a ranger plugin: https://github.com/gsamokovarov/jump-ranger. Don't think it needs a core integration for now. Let's see how mature ranger will become!

I'm keeping the issue open if there are any issues with the plugin. Tested it a bit locally, but I'm not a ranger user.

**Comment by jcklpe** [comment]
Rad! Thank you so much!

**Comment by jcklpe** [comment]
Seems to work great, at least from the `:` ranger command console. 

I tried integrating the r() zsh function [[from the autojump integration]](https://github.com/fdw/ranger-autojump/blob/master/ranger-autojump.plugin.zsh) but it doesn't seem to be working. 

```

# Add a `r` function to zsh that opens ranger either at the given directory or
# at the one jump suggests
r() {
  if [ "$1" != "" ]; then
    if [ -d "$1" ]; then
      ranger "$1"
    else
      ranger "$(j $1)"
    fi
  else
    ranger
  fi
        return $?
}
```

I originally tried it with jump but that just did a fuzzy search and returned the directory. That seems to be expected behavior for jump though from the man page for jump which also includes mention of cd being an available parameter to be passed. 

I assumed that meant that j was a wrapper which performed jump and that then pipes the directory results to the cd command. 

But when I pass it j it just returns a response saying "that directory doesn't exist". Any thoughts on what I'm doing wrong etc?

**Comment by gsamokovarov** [comment]
`j` is a shell function and it automatically `cd`'s to the directory and does not print anything. The `jump` binary itself has several commands that make `j` work. `jump cd` prints the actual directory from the input, so you can use it:

```zsh
# Add a `r` function to zsh that opens ranger either at the given directory or
# at the one jump suggests
r() {
  if [ "$1" != "" ]; then
    if [ -d "$1" ]; then
      ranger "$1"
    else
      ranger $(jump cd $@)
    fi
  else
    ranger
  fi
  return $?
}
```

**Comment by gsamokovarov** [comment]
Cool! Glad it works for you.
