### ISSUE TITLE
Offer: Open Source Design project

### ISSUE THREAD

**Issue by jcklpe** [gsamokovarov/jump#34]
Hi, 

Big fan of jump. I think it's great. 

It's also a bit hard to find, since it's name is so similar to autojump. 

I think it's also worth getting some real branding work done. I'm a designer who has switched to code, but I'm still very much interested in design and one of the things I'm trying to do to help give back to the open source community is through a project I'm working on called Open Source Branding: https://github.com/jcklpe/Open-Source-Branding

I'm specifically working on this stuff through a repo and using github issues to format things because I'm interested in using this project as a means of demonstrating traditional, decentralized developer tools repurposed for design work. Please consider opening a ticket here and I'd love to help out anyway I can! : https://github.com/jcklpe/Open-Source-Branding/issues/new?template=branding-request.md

**Comment by gsamokovarov** [comment]
I think this is awesome! Jump does need better branding. My English isn't the best and even the gif on the README needs some proper love to look better. Both documentation and graphics do need I refresh. I will apply for sure! 🙏

**Comment by gsamokovarov** [comment]
I have opened the issue: https://github.com/jcklpe/Open-Source-Branding/issues/2.
