### ISSUE TITLE
prebuilt binary for raspi

### ISSUE THREAD

**Issue by Micha-Btz** [gsamokovarov/jump#35]
Hi there,

I like your tool a lot, so it would be nice, to have this on my raspi too. It's a raspberry 3B+ which running dietpi:

```
dietpi@DietPi:~$ uname -a
Linux DietPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

root@DietPi:/var/# dpkg --print-architecture
armhf
```

Would be great, if you can provide a Debian package for armhf architecture or at least try to explain me how I get it compiled.

Thanks Micha

**Comment by gsamokovarov** [comment]
As a starting point, I have compiled a static linux ARM binary at: https://github.com/gsamokovarov/jump/releases/tag/v0.22.0. Put it somewhere in `$PATH` as `jump` and you should be good to go.

Please tell me if the binary works for you. All my RPI's are broken at this point. 😅

**Comment by Micha-Btz** [comment]
basically it worked, but I haven't time to test further.

**Comment by gsamokovarov** [comment]
Cool, please do report if you experience any troubles. I'm gonna close the issue for now.
