### ISSUE TITLE
Install v0.23.0 on ubuntu 18.04, error: Merg`status file could not be parsed or opened.

### ISSUE THREAD

**Issue by shaohua-deng** [gsamokovarov/jump#37]
This happens on two computers of mine.  
```
$ sudo dpkg -i ./jump_0.23.0_amd64.deb 
tar: Archive is compressed. Use -j option
tar: Error is not recoverable: exiting now
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive ./jump_0.23.0_amd64.deb (--install):
dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./jump_0.23.0_amd64.deb
```

While the same command succed with v0.22.0
```
$ sudo dpkg -i ./jump_0.22.0_amd64.deb 
(Reading database ... 96811 files and directories currently installed.)
Preparing to unpack ./jump_0.22.0_amd64.deb ...
Unpacking jump (0.22.0) over (0.22.0) ...
Setting up jump (0.22.0) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
```
My OS information:
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by gsamokovarov** [comment]
Did you get the packages from the links in the README?

**Comment by shaohua-deng** [comment]
Yes. Here is the command from history
```
wget https://github.com/gsamokovarov/jump/releases/download/v0.23.0/jump_0.23.0_amd64.deb
```
I tried several times on two machines, It's unlike a download issue.  
The binary file jump_linux_amd64_binary is good, I can run it directly.

**Comment by gsamokovarov** [comment]
It's probably an issue with FPM, as I build them from my local macOS machine. I'll try and rebuild the **deb**s and test them under Ubuntu or Debian.

**Comment by gsamokovarov** [comment]
Reproduced the issue, happens on Linux as well. Will check the `fpm` build command and re-upload the debs once fixed.

**Comment by gsamokovarov** [comment]
Thanks for the catch! The problem was that the latest FPM version (1.11.0) yields bad DEB packages. I have re-packaged the Debian release and re-uploaded it. Can you test it and tell me whether it's okay?

**Comment by shaohua-deng** [comment]
It's good now.  I installed  the deb file with command dpkg -i

**Comment by gsamokovarov** [comment]
Great!
