### ISSUE TITLE
”status --is-interactive; and . (jump shell | psub)“ is not working in fish of  Mac Mojave

### ISSUE THREAD

**Issue by mail2fish** [gsamokovarov/jump#38]
I have to use the command which like below:

```
status --is-interactive; and source (jump shell fish | psub)
```

**Comment by mail2fish** [comment]
```
status --is-interactive; and . (jump shell | psub)
```

will output error like below

```
/var/folders/lx/l92vp3f92zj3syxygbhkpcrr0000gn/T//.psub.kBKoDsbPLV: Command substitutions not allowed
```

**Comment by gsamokovarov** [comment]
I'm actually running fish shell. Can you give me a bit more context about your system and fish version?

**Comment by mail2fish** [comment]
```
$ fish --version
fish, version 3.0.2
```

<img width="181" alt="image" src="https://user-images.githubusercontent.com/349836/59171136-3b5e1700-8b74-11e9-8c80-273e4bc45666.png">

**Comment by mail2fish** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/349836/59171181-6fd1d300-8b74-11e9-8e01-8e67eb35b398.png">

**Comment by mewmew** [comment]
I get the same error, running on Arch Linux with fish version 3.0.2.

After adding the line to `~/.config/fish/fish.config`, I get this error when starting a new fish shell:
```
/tmp/.psub.DBdse2QvUH: Command substitutions not allowed
from sourcing file /tmp/.psub.DBdse2QvUH
	called on line 359 of file /usr/share/fish/config.fish

in function “.”
	called on line 107 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

source: Error while reading file “/tmp/.psub.DBdse2QvUH”
```

```
u@x220 ~> tail .config/fish/config.fish 
# Autojump using https://github.com/gsamokovarov/jump
status --is-interactive; and . (jump shell | psub)
```

**Comment by gsamokovarov** [comment]
You are probably using an older version of jump, the newer ones use `source` instead of `.` , will be closing this issue but feel free to reopen it if there are still problems with the fish integration.

**Comment by khamo** [comment]
I am running starship in fish and I put
`status --is-interactive; and source (jump shell fish | psub)`
in my fish config file yet when I try to utilize jump it tells me the database is empty and that I haven't integrated yet.

**Comment by gsamokovarov** [comment]
You do sound like you are integrated but haven't entered directories in the new shell session that has been integrated with `jump`.

If you still think the Fish integration is the issue, you may try `jump shell fish | source` as this is the simpler way to integrate jump in newer Fish shells. I'll go ahead and promote this integration in the README.
