### ISSUE TITLE
Not working well on zsh on Mac OS X

### ISSUE THREAD

**Issue by sierisimo** [gsamokovarov/jump#4]
Ok, I'm not sure about how to explain this issue, because I have no background.

But, I'll try: 

I just installed via `brew install jump` and then `echo 'eval "$(jump shell zsh)"' >> ~/.zshrc`

Then I tried with: `exec -l $SHELL` to replace my current shell and go to a directory `j SomeDirectory_A`

Nothing happend... I'm still at my home directory.

So... maybe the `exec` didn't make the magic. I closed all the tabs and terminal. 

Open a new one.

`j SomeOtherDirectoryAtMyHome_B`

Nothing.

If I check: `which j`

```
j () {
	local dir="$(jump cd $@)"
	test -d "$dir" && cd "$dir"
}
```

and if I try: `jump cd SomeDirectory_A` ... nothing happens.

and then, I tried again: `j SomeOtherDirectoryAtMyHome_B` and then it moved me to `SomeDirectory_A`

I really want to use your utillity, because your idea looks great.

**Comment by sierisimo** [comment]
Sorry I opened the Issue as soon as I installed, I realize that the command is using the `cd` history from the moment that is installed and has no local info. But still thinking it's a little issue that other might find.

**Comment by gsamokovarov** [comment]
Yeah, you gotta give it some time for the initial database to build itself. Also, if you are using oh my zsh, you may experience autocompletion problems. I'm still looking into that.
