### ISSUE TITLE
disable auto cleaning

### ISSUE THREAD

**Issue by aeosynth** [gsamokovarov/jump#41]
I mount and unmount drives regularly, so I would like to disable automatic cleaning, since the directory is probably just not mounted.

**Comment by gsamokovarov** [comment]
For now, I have avoided configuration switches as a design goal. It's easy to do actually, but let me think about this one as well.

**Comment by gsamokovarov** [comment]
Okay, I'll still ship with my preferred defaults, but open up a CLI subcommand `jump config` that can set global configuration flags. I'll write this file to disk as well, so it can be committed in GitHub dotfiles and the likes. This will tie in XDG support, which was also pending for a while.

I can't give you a strict timeline, but I think I can cover your ides from this and the previous issue (#40) with `jump config`.

**Comment by gsamokovarov** [comment]
This is done in the master branch. WIll roll it a new release soon!

**Comment by gsamokovarov** [comment]
Hey @aeosynth, this is a bit late but you can stop jump from cleaning up the missing entries with:

```bash
jump settings --preserve=true
```

You'll need the latest jump build `0.30.1` from https://github.com/gsamokovarov/jump/releases/tag/v0.30.1
