### ISSUE TITLE
Evict Last Jump

### ISSUE THREAD

**Issue by sabrehagen** [gsamokovarov/jump#43]
**Feature Request**: Evict last jump.

I find myself running `j target-dir; j` all too often, and would like the ability to evict the first result returned by `j target-dir` so that I don't encounter it again in future.

**Comment by sabrehagen** [comment]
Any possibility of this?

**Comment by gsamokovarov** [comment]
Sorry for the late response. I have been trying to tackle this for a while now. I have some work in progess in the [`jump-penalty-for-bad-matches`](https://github.com/gsamokovarov/jump/tree/jump-penalty-for-bad-matches) branch, but it's not where I want it to be at the moment.

The idea is to make `j` a bit more clever and reduce the score of the previous match. I'm yet to find  a good score reducing algorithm. I will feature an attempt to solve this in the next Jump release for sure. It will take a while, but I'm on it!

**Comment by sabrehagen** [comment]
Any update on the release of this? Still bugs me daily :disappointed:

**Comment by gsamokovarov** [comment]
Can you give me a bit more context about your issue? While I'm still working on the automatic `j` hint (de)scoring, you may already have some tools at your disposal in the form of `jump forget` or `jump pin`.

- `jump forget` lets you remove a directory out of the scoring database.
- `jump pin` lets you "pin" (hardcode) a search term `j term` to a specific directory. This may help you.

Run `jump forget --help` or `jump pin --help` for information about their usage.

**Comment by sabrehagen** [comment]
Thanks for the extra info! My context is I land in directories I will never
use again, and then need to 'j' again to get to the desired directory on
the second attempt.

It looks like I want forget, rather than your de-scoring improvement. I
expect I will want de-scoring one day, but for now forget is perfect for my
context.

I missed this as there was no documentation on these commands in the
readme. Command enumeration in the docs would help new comers!

**Comment by gsamokovarov** [comment]
Documentation is something we can improve for sure! If you want to help out and describe them in the README and the man page, this will help a lot.

Thanks for using jump! ❤️
