### ISSUE TITLE
Disable `jump top` from printing scores

### ISSUE THREAD

**Issue by amosbird** [gsamokovarov/jump#46]
Hi, this update breaks all my scripts related to `jump top`. Could you make an option to print the additional score column and default to the old behavior?

**Comment by gsamokovarov** [comment]
Okay, this makes sense. I only enabled it to debug internal issues, will put it behind a flag. :+1:

**Comment by gsamokovarov** [comment]
Should be fixed by a0300949dc74e97ab22774014e640b34f7c126cb. I'll close the issue now, but feel free to reopen it if something's wrong.
