### ISSUE TITLE
Question: listing matches on tab completion not a design goal?

### ISSUE THREAD

**Issue by jcassee** [gsamokovarov/jump#47]
Coming from `j` being aliased to `fasd_cd`, I'm trying out Jump to see if I like it more. I'm used to sometimes typing `j someth<tab>` to quickly go to a directory called "something" when there are multiple on my system and I don't want to think beforehand what the correct search terms would be.

It seems this was a use-case for Jump in the past but it has been removed. Was that a design decision?

**Comment by gsamokovarov** [comment]
We still have autocompletion, what shell are you using? I have seen problems with `zsh` and `oh-my-zsh` as they already provide autocompletion for `autojump` which collides with the `j` helper.

**Comment by jcassee** [comment]
I'm using ZSH. When I press <tab>, the shell completes the single match that would be used if I would just press <enter>. I was hoping for a short ordered list of matches.

About `fasd_cd`: I meant Fasd, a different Jump-like utility: https://github.com/clvv/fasd. I am not using a `fast_cd` alias, I used to alias `j` to `fasd_cd`, as a test I aliased it to Jump using `eval "$(jump shell zsh)"`.

Some examples:

Currently, with Jump, I see this:
`$ j autom` _tab_
↓↓↓
`$ j /home/joost/dev/automat`

Fasd used to do this:
`$ j autom` _tab_
↓↓↓
```
$ j autom /home/joost/dev/automat
/home/joost/dev/automat
/home/joost/dev/automat/automat
/home/joost/dev/infra/environments/development/automat
/home/joost/dev/infra/environments/production/automat
```

I have made sure all of those `automat` directories are in Jumps `scores.json`:
```
$ jq -r '.[].Path' <~/.jump/scores.json
/home/joost/dev/automat/automat
/home/joost/dev/infra/environments/development/automat
/home/joost/dev/infra/environments/production/automat
/home/joost/dev/automat
[...]
```

**Comment by gsamokovarov** [comment]
Used to support multiple matches in some shells autocompletion, but unified it to one match for all (https://github.com/gsamokovarov/jump/commit/f26678ffacc9135c4ba0d9cc05b59b39e6a3fee8.) 

We support features like deep matching: `j prod/aut` will go to `/home/joost/dev/infra/environments/production/automat` and the tab completion can verify that for you. I'm open to refining the autocompletion, but what do you get from it? More visibility where you'll land?

**Comment by jcassee** [comment]
Interesting that it existed but was removed.

Indeed, it's a "look before you leap" thing. Like you say, it is possible to be unambiguous, but I don't need to be if I can bring up "the menu". It feels comforting. :slightly_smiling_face:

I'm not sure whether I'm just used to my old ways, or whether it would be a useful feature in Jump.

**Comment by gsamokovarov** [comment]
I'm not using autocompletion, as I use jump to save keystrokes and a hit to the tab is a hit to the tab 😄 

I'm about to release a new version of jump this month, and I'm not sure I can squeeze this in, but I can try and revisit the autocompletion afterward. It's something my friends also use, so it's gonna be beneficial for the people that depend on it.

Is the autocompletion stopping you from using jump at the moment? Do you have any other impressions?

**Comment by jcassee** [comment]
Jump seems to work very well. I like the separate path matching, in combination with (I think?) the preference for shorter matches. The autocomplete is not stopping me from using Jump, let's see how I feel about it in a couple of days. :-)

Thanks!

**Comment by gsamokovarov** [comment]
Cool, will close this issue for now. Feel free to open other issues, if you have more questions! ✌️
