### ISSUE TITLE
PROMPT_COMMAND clobbers $?

### ISSUE THREAD

**Issue by greygore** [gsamokovarov/jump#5]
For people who test the return value of the previous command to alter their prompt, ```eval "$(jump shell bash)" will clobber that return value so that every command seems to exit successfully.

Swapping the order:
```bash
[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="$PROMPT_COMMAND;__jump_prompt_command"
}
# instead of
[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}
```
seems to fix the issue without changing the behavior as far as I can tell.

**Comment by gsamokovarov** [comment]
Can you give a bit more context? I'm still being able to access `$?` for the return value in `bash` as usual.

**Comment by greygore** [comment]
Yes, that confused me too. I assume PROMPT_COMMAND is executed in a subshell which preserves the value of ```$?``` outside of that. The problem comes _inside_ that PROMPT_COMMAND subshell. If I want to alter my bash prompt in response to the success or failure of the last command, I need to do is store that return value to prevent clobbering it myself:

```sh
function my_prompt_func() {
    local code=$?
    local dir=$(pwd)

    if [ $? -eq 0 ]; then
        PS1="$dir ✔ $"
    else
        PS1="$dir ✕ $"
    fi
}

PROMPT_COMMAND=my_prompt_func
```
(Or a [real life example](https://github.com/greygore/dotfiles/blob/master/config/bash/prompt#L155-L160))

Of course, when I add ```eval "$(jump shell bash)``` it changes that to ```PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"```, which means that ```$?``` inside of ```my_prompt_func``` is the exit code of ```__jump_prompt_command``` and not the command last executed by the user.

Since it looks like you're just hooking into that to adjust the score, it seems like you could reorder those PROMPT_COMMANDs to put ```__jump_prompt_command``` last, which is what I've done in [my workaround](https://github.com/greygore/dotfiles/blob/master/config/bash/.bash_profile#L35-L43). Alternately, you could return the original exit code from ```_jump_prompt_command```, or preserve the last exit code in an environmental variable, but those both seem unnecessary

**Comment by gsamokovarov** [comment]
I get you now! Will reorder it for the next version. Haven't thought that someone may require the return value somewhere in `PROMPT_COMMAND`.

Thanks for the detailed report!

**Comment by gsamokovarov** [comment]
Hey @greygore, can you try the changes in f124fa4a8587447a3d8875e251982e8cbfc5fc1d and see whether they work for you? A lot of tools inject themselves into the beginning of `PROMPT_COMMAND` and if I inject myself last I have to be weary of `;;`.
