### ISSUE TITLE
 How do you change the directory of the parent process?

### ISSUE THREAD

**Issue by isshe** [gsamokovarov/jump#53]
I want to implement the `cd` command with python, but I don't know how to modify the working directory of the parent process (shell).😂

**Comment by gsamokovarov** [comment]
`jump cd` only gives you the path you need to jump to. `j` is a shell function that actually, `cd`'s to it:

https://github.com/gsamokovarov/jump/blob/2c3d409006a298c2372e2d8ef740e1ff6e2a444c/shell/bash.go#L21-L22
