### ISSUE TITLE
RPM refuses to install on Fedora due to OS is specified as darwin

### ISSUE THREAD

**Issue by snaggen** [gsamokovarov/jump#54]
The tag OS in the file jump-0.30.1-1.x86_64.rpm,  as reported by, 
`rpm -qp --qf '%{OS}\n' *.rpm`
says `darwin`, which makes it impossible to install on a regular Fedora Linux.

**Comment by gsamokovarov** [comment]
Holy moly, let me rebuild the packages in a Linux VM.

**Comment by gsamokovarov** [comment]
@snaggen I have rebuilt the packages, can you try again?

**Comment by snaggen** [comment]
The new packages work! Thanks for a quick fix!

**Comment by gsamokovarov** [comment]
Thanks for trying jump! Hope you like using it. 👌
