### ISSUE TITLE
Escaping hyphens and apostrophes and other 

### ISSUE THREAD

**Issue by jorgsk** [gsamokovarov/jump#60]
Hi! Thanks for the excellent tool.

I'm syncing some remote directories with Onedrive that have hyphens in their names. Jumping to these does not seem to work, at least on my MacOS installation. E.g. "j search" -> "j /some/remote/dirname - with hyphen/search". Whitespace alone seems to be handled fine, as in "j search" -> /some/dir with whitespace/search". I also noted that an apostrophe also does not work, as in "j search" -> "j /not/sure/why/you'd make a dirname like this but it's what I get".

Is it possible to escape these odd but allowed characters in directory names?

**Comment by gsamokovarov** [comment]
I'm pretty sure the directory names with apostrophes and the like are handled fine in Jump's JSON database, however, these could be a problem in the shell integrations. What shell are you using?

**Comment by jorgsk** [comment]
I'm using bash -- but I found out something more about what's the issue here. Jumping to directories with hyphens does actually work when I don't tab-complete the target directory. So if I just type "j search" I do land at the right target even if a parent directory has hyphens. I'd gotten used to tab completing the searches in order to see the full path, and when I do that it doesn't work. I just tested with zsh but I've probably not got it set up right because tab completion didn't do anything there. Completion without tab worked with hyphens in zsh too as for bash.

So I guess the question is if jumping to a directory after tab completion a feature in jump or something bash specific?

**Comment by gsamokovarov** [comment]
It could be the missing escaping when generating the completion hints. Can you try changing this line to:

https://github.com/gsamokovarov/jump/blob/cedde1e93ad386fbce0134e34988b0022fd42bae/shell/bash.go#L17

```
jump hint "$term"
```

You don't need to compile jump, but replace the integration in you bashrc from `eval "$(jump shell bash)"` to the wit bash script lines inside of the **`** block.

**Comment by jorgsk** [comment]
My .bashrc contained the lines
`eval "$(jump shell)"` (from the front page instructions)
When I first tried to change this to 
`eval "$(jump shell bash)"`
I got the same behavior as before.
Further changing this line to 
`eval "$(jump hint $term)"`
does not evaluate well, and I get an error when starting bash. Perhaps I didn't write what you intended?

**Comment by gsamokovarov** [comment]
I'll test it locally and put a build for you to test as well. It will be easier than writing the integration script manually.

**Comment by gsamokovarov** [comment]
I have tested I locally and have a fix for this. Will release a new version of Jump tomorrow with it.

**Comment by jorgsk** [comment]
Thanks! Will test when out :)

**Comment by gsamokovarov** [comment]
Thank you for bringing this up! This was a security issue as well. If a cleverly named directory existed in you jump database, going to the directory by following the autocompletion could have been dangerous!  You can spawn shell commands with the directory name and that's not good. Again, thanks for the notice.

The autocompletion should be fixed for such cases in the new release, [`0.4.0`](https://github.com/gsamokovarov/jump/releases/tag/v0.40.0). Read the release notes for more details. I have attached a `jump_osx` OSX binary, because it will take a while for brew to pick up the new release.
