### ISSUE TITLE
Integration documentation outdated?

### ISSUE THREAD

**Issue by w0rmr1d3r** [gsamokovarov/jump#62]
When reading the README.md file it says that I should append `eval "$(jump shell)"` into my `~/.zshrc` file.
Yet, doing it and closing and opening the terminal does nothing, as if it wasn't done.

And Jump suggests that I should run `jump shell` for Integrations. After doing so, it says:
```
# Put the line below in ~/.zshrc:
#
#   eval "$(jump shell zsh)"
#
# The following lines are autogenerated:

__jump_chpwd() {
  jump chdir
}

jump_completion() {
  reply="'$(jump hint "$@")'"
}

j() {
  local dir="$(jump cd $@)"
  test -d "$dir" && cd "$dir"
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

compctl -U -K jump_completion j
```

Should the documentation say -> add this `eval "$(jump shell zsh)"` instead? Or run `jump shell` the first time and follow the instructions?

Have I missed anything? Thank you!

**Comment by gsamokovarov** [comment]
`jump shell` is а command that outputs the shell integration code. It can automatically infer the current shell based on the value of the `$SHELL` value which is usually correct. It can be mangled when you run `bash` session inside your regular `zsh` one, as a single example. If you have a problem with the automatic guess, you can be more explicit and tell `jump shell` which shell integration code to print with `jump shell zsh` or `jump shell fish`, etc.

If you have issues with `jump`'s integration I'd start with running `which j`, if it's not a shell function then the integration code hasn't run. Are you sure you're running `zsh` or you have setup'd `jump` for the proper user?

Can you give me a bit more information about your environment? OS, zsh version and an excerpt of the ZSH configuration file can help me.

**Comment by w0rmr1d3r** [comment]
Hello @gsamokovarov !

More information:
OS -> macOS Catalina 10.15.7
zsh version -> zsh 5.7.1 (x86_64-apple-darwin19.0) (obtained from running `zsh --version`)
When running `echo $SHELL` it prompts `/bin/zsh`
When running `which j`, it prompts:
```
j () {
	local dir="$(jump cd $@)"
	test -d "$dir" && cd "$dir"
}
```

I have installed j using brew, as in the README.md -> `brew install j`

What I did, following this repo's README.md, after installing j (with brew), I appended `eval "$(jump shell)"` in my `.zshrc` file. But it did nothing.

I had to run `jump shell` and add `eval "$(jump shell zsh)"` in my `.zshrc` file instead of `eval "$(jump shell)"`, which is what the README.md told me to do, to add the latter.
I have j running and it's awesome, my question is, is the documentation outdated regarding the installation?

Thank you @gsamokovarov !

**Comment by gsamokovarov** [comment]
I'm glad you like `jump` and it seems to be properly running now. I think the documentation is fine for now, as I haven't got much integration complaints, but I'll keep an open mind about it.

Happy jumping!

**Comment by JekRock** [comment]
@w0rmr1d3r how do you start your `zsh`? If you start it from `bash` (for example, by adding `zsh` at the end of `.bashrc`), then `jump` will detect it as `bash` not `zsh`. I've just got the same situation here.

**Comment by gsamokovarov** [comment]
You can be specific about the shell integration, and don't let jump infer it by the `$SHELL` env with `jump shell zsh`. Is this working for you @JekRock?

**Comment by JekRock** [comment]
@gsamokovarov that works, not a problem at all. Just suggested a possible reason for the behavior described in this issue.

Thanks for the cool tool!
