### ISSUE TITLE
Clear non-existing directories.

### ISSUE THREAD

**Issue by amosbird** [gsamokovarov/jump#7]
Does `jump` support garbage collection?

**Comment by gsamokovarov** [comment]
Yes, if the directory you try to jump to no longer exists, it removes the entry from the internal database and jumps to the next closest match.

[This](https://github.com/gsamokovarov/jump/blob/94a908d15e17e39d969327b885bb0510a3ca9790/cmd/cd.go#L37-L44) is where it happens.

**Comment by amosbird** [comment]
oh, I don't rely on `jump` to change directory for me. I just use `jump top` to get the list, and then filter it using `fzf`.

**Comment by gsamokovarov** [comment]
Ah, it does happen on `jump cd`, though and not in a background process or something like that. The main reasoning for doing it on `cd` is the entry you want to check for existence may be on a remote share. That may hang up for quite a while if the share is transient. So if we are to check every entry you ever been though to clean them up, maybe we can hang.

I can try to do global cleaning on the `top` command though and see if anyone complains. If no one uses `jump` in such environments, it may be fine.

**Comment by amosbird** [comment]
well, I think manual clean is fine. Maybe a `jump clean` subcommand.

**Comment by gsamokovarov** [comment]
This is fair. I can do that.

**Comment by gsamokovarov** [comment]
I have introduced `jump clean` and will prepare a new release in a bit.

**Comment by gsamokovarov** [comment]
@amosbird the new release is out, you can upgrade from brew or get the linux packages on: https://github.com/gsamokovarov/jump/releases/tag/v0.8.0

**Comment by amosbird** [comment]
great, thanks!
