### ISSUE TITLE
jump 0.41.0 debian packages are broken

### ISSUE THREAD

**Issue by Findus23** [gsamokovarov/jump#70]
I just noticed this and thought I'd mention it:
```
➜ sudo apt install ./jump_0.41.0_amd64.deb
➜ jump
Failed to execute process '/usr/bin/jump'. Reason:
exec: unknown error (errno was 8)
The file '/usr/bin/jump' is marked as an executable but could not be run by the operating system.
➜  file '/usr/bin/jump'
/usr/bin/jump: Mach-O 64-bit x86_64 executable
```

Is it possible that the wrong executable slipped into the package?

Thanks for your great tool!

**Comment by gsamokovarov** [comment]
I have re-created the packages and they should be good now.

**Comment by Findus23** [comment]
Personally I'm not that familiar with snap and similar package management tools, so I can't really comment on that.

But the new package works perfectly fine, so thanks for the fast help!
