### ISSUE TITLE
Release the binary of jump v0.41.0 for macOS

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gsamokovarov/jump#72]
Thank you for your great project!
I have a request.

https://github.com/gsamokovarov/jump/releases/tag/v0.41.0

There is no binary of jump v0.41.0 for macOS.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/13323303/165284847-de312027-eaa5-44c8-ba3b-50d6f13102de.png">

On the other hand, there are binaries for macOS in v0.40.0 or earlier.

https://github.com/gsamokovarov/jump/releases/tag/v0.40.0

<img width="335" alt="image" src="https://user-images.githubusercontent.com/13323303/165284899-ad5e63c1-b87a-469c-bd76-92f4ebd13e6b.png">

Could you release the binary of v0.41.0 for macOS?

**Comment by gsamokovarov** [comment]
I have uploaded it. Do you need macOS ARM (Apple M1+) compatible builds?

**Comment by gsamokovarov** [comment]
There you go: https://github.com/gsamokovarov/jump/releases/download/v0.41.0/jump_osx_arm64

**Comment by suzuki-shunsuke** [comment]
Thank you so much!

**Comment by gsamokovarov** [comment]
No worries, thank you for using Jump! 🙇
