### ISSUE TITLE
windows builds

### ISSUE THREAD

**Issue by jyannick** [gsamokovarov/jump#73]
Is it by design that the windows binary is not published for the latest couple of releases ?

I've tried building from source on windows, and everything seems to work fine. It would be easier for windows users to grab the binary directly, instead of building from source.

**Comment by gsamokovarov** [comment]
@jyannick we have [official Windows builds for `0.50.0`](https://github.com/gsamokovarov/jump/releases/tag/v0.50.0).

**Comment by jyannick** [comment]
Awesome, thank you very much!

In terms of package manager, I personally use `chocolatey`. But it seems `winget` and `scoop` are gaining a lot of momentum lately, so I might switch one day.
