### ISSUE TITLE
Release assets of jump v0.50.0 for Linux

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gsamokovarov/jump#74]
Thank you for your great project!
I have a request.

Could you release assets for Linux?

I found assets for Linux aren't released at v0.50.0.

https://github.com/gsamokovarov/jump/releases/tag/v0.50.0

<img width="335" alt="image" src="https://user-images.githubusercontent.com/13323303/177225002-bb41a8e6-436f-4f48-94d5-cf927179c46c.png">

On the other hand, assets for Linux has been released at v0.41.0.

https://github.com/gsamokovarov/jump/releases/tag/v0.41.0

`jump_linux_amd64_binary`

<img width="284" alt="image" src="https://user-images.githubusercontent.com/13323303/177225024-d9326bc5-3e61-465e-8a30-449a8ff00bf3.png">

**Comment by gsamokovarov** [comment]
I forgot them the last release too, did't I? 😅 I'll upload them in a bit.

**Comment by gsamokovarov** [comment]
@suzuki-shunsuke I have uploaded linux binaries.

**Comment by suzuki-shunsuke** [comment]
Thank you!
