### ISSUE TITLE
v0.51.0 - release binaries request

### ISSUE THREAD

**Issue by presianbg** [gsamokovarov/jump#75]
Hi,

Thanks for the awesome `J` project! Any plans to release pre-build binaries for the latest v0.51.0 ?

Cheers,
PY

**Comment by gsamokovarov** [comment]
Thanks for the nudge, I will create them and upload them at https://github.com/gsamokovarov/jump/releases/tag/v0.51.0.

Will close the issue when I do.

**Comment by gsamokovarov** [comment]
Sorry for the hold-up, the binaries are up at https://github.com/gsamokovarov/jump/releases/tag/v0.51.0.
