### ISSUE TITLE
ARM version in brew

### ISSUE THREAD

**Issue by mvasin** [gsamokovarov/jump#76]
Hi,

when installing on an M1 Mac via Homebrew, I get

```
% brew install jump
Warning: Treating jump as a formula. For the cask, use homebrew/cask/jump
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

**Comment by gsamokovarov** [comment]
From that output, I suspect that `brew` itself runs under Rosetta 2. Is that the case?

**Comment by mvasin** [comment]
Hi Genadi,

to the best of my knowledge, Homebrew is a Ruby app, and there is an arm version of ruby. Here's what is says on my machine:

```
% ruby -v
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin22]
```

**Comment by gsamokovarov** [comment]
Homebrew is a Ruby app, but macOS supports universal binaries that carry both x86 and arm64 versions of a program. This is the case for the system ruby installation in macOS.

```
-> file /usr/bin/ruby
/usr/bin/ruby: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/ruby (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/ruby (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

I am running an ARM Mac and have jump installed from homebrew. This should be a problem with your session or brew installation. Closing this issue for now.
