### ISSUE TITLE
command not found: jump

### ISSUE THREAD

**Issue by jynnie** [gsamokovarov/jump#77]
Hello! I have installed jump and put `eval "$(jump shell)"` in my `~/.zshrc` file. While typing `jump --version` works fine; I'm getting `.zshrc: command not found jump` whenever I open my terminal.

I've checked that I don't have `jump` in my plugins array in `.zshrc`. I did previously have it there, but then removed it. But I can't get the `.zshrc` and `j` commands to work.

**Comment by jynnie** [comment]
I fixed this by replacing `eval $(jump shell)` with the auto-generated code in my `.zshrc`. Not sure why that works but it does!

Thank you for this awesome package by the way. I've used this for years and its amazing. Only having a little trouble with reinstalling it.

**Comment by gsamokovarov** [comment]
You can check your `$SHELL` variable, which jump uses to infer the shell and its integration code. It may say `bash` or something else if you start your zsh from another shell and try to use  You may also give a hint about your shell to `jump shell` like `eval "$(jump shell zsh)"`.
