### ISSUE TITLE
Consider adding an ability to create aliases within jump

### ISSUE THREAD

**Issue by dmtrKovalenko** [gsamokovarov/jump#80]
I am very gratefully using jump and was super satisfied until it started leading me to the fake directories for the searches I get used to. 

My case is the following: I got used to type `j sourcing` which for a few months was leading me to my directory `~/dev/myproj/.../sourcing-app` but at some point, I visited some deep nested autogenerated directory which looks like `~/dev/myproj.../tests/sourcing/blablabla-testname.spec.ts-snapshots` and now I am suffering because every time I use my very useful command it leads me to this nonsense I need to type j j j to get to my working directory.

I would be very happy if it will be possible to do something like j override sourcing <PATH> and it will always send me to the directory I expect

**Comment by gsamokovarov** [comment]
Hey, sorry for the super late reply... We do have such functionality, it's called jump pins!

```
$ jump pin
Usage: jump pin term

No term specified. Please specify a term that will be permanently
attached to the current directory. If the term contains spaces, they
will be normalized to OS separators.
```

Go to the directory you want to pin and call `jump pin alias-term-hoes-here`. `jump pins` will list the current pins. `jump unpin term` will unpin a term (the alias).

See the [release notes of 0.20.0] for(https://github.com/gsamokovarov/jump/releases/tag/v0.20.0) for more information. Please, do give me feedback about the CLI UX as well.

**Comment by dmtrKovalenko** [comment]
This is wonderful! But the problem that there is nothing about such a useful command at all neither in the readme nor in the man page. I could make a PR to add it to the docs
