### ISSUE TITLE
scores.json becomes malformat when disk is full

### ISSUE THREAD

**Issue by amosbird** [gsamokovarov/jump#9]
I just accidentally fill my disk and crashes `jump`. It writes a partial scores.json file and all subsequent calls ending up with ` ❯ err: unexpected EOF`

**Comment by gsamokovarov** [comment]
Thanks for the report! This is interesting, maybe I can skip the disk space errors? Did the file become corrupt?

**Comment by amosbird** [comment]
yes, it's truncated.

**Comment by gsamokovarov** [comment]
I'ma move the discussion in the PR.
